In [4]:
import pandas as pd

df = pd.read_csv("employees.csv")

print(df)

    Name  Age  Gender  Salary  Experience
0   Aman   23    Male   25000           1
1  Priya   25  Female   30000           2
2  Rohit   28    Male   45000           4
3  Sneha   24  Female   28000           2
4    Raj   30    Male   55000           5

In [5]:
df.shape

(5, 5)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Gender      5 non-null      str
 3   Salary      5 non-null      int64
 4   Experience  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

In [7]:
df.describe()

             Age       Salary  Experience
count   5.000000      5.00000    5.000000
mean   26.000000  36600.00000    2.800000
std     2.915476  12856.90476    1.643168
min    23.000000  25000.00000    1.000000
25%    24.000000  28000.00000    2.000000
50%    25.000000  30000.00000    2.000000
75%    28.000000  45000.00000    4.000000
max    30.000000  55000.00000    5.000000

In [8]:
df["Gender"].value_counts()

Gender
Male      3
Female    2
Name: count, dtype: int64

In [9]:
df.head()

    Name  Age  Gender  Salary  Experience
0   Aman   23    Male   25000           1
1  Priya   25  Female   30000           2
2  Rohit   28    Male   45000           4
3  Sneha   24  Female   28000           2
4    Raj   30    Male   55000           5

In [17]:
import pandas as pd


df = pd.read_csv("har.csv")

print(df)

      "Name": "Harshita"   "Aman"   "Priya"  Unnamed: 3
0              "Age": 20       21        22         NaN
1        "Salary": 25000    30000     35000         NaN

In [18]:
df.head()

      "Name": "Harshita"   "Aman"   "Priya"  Unnamed: 3
0              "Age": 20       21        22         NaN
1        "Salary": 25000    30000     35000         NaN